name: PipelineWorkFlow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Azure Pipeline
    runs-on: windows-latest
    steps:
      - name: Azure Pipeline Action
        uses: azure/pipelines@v1
        with:
          azure-devops-project-url: https://dev.azure.com/microsoftazure4400329/AzurePipelineGithubIntegrationProject
          azure-pipeline-name: StarkIndustries440.PipelineGithubIntegrationApp
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }} 

