name: PipelineWorkFlow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Azure Pipeline
    runs-on: Default
    steps:
      - name: Azure Pipeline Action
        uses: azure/pipelines@v1
        with:
          azure-devops-project-url: https://dev.azure.com/microsoftazure4400329/AzurePipelineGithubIntegrationProject
          azure-pipeline-name: ${{ secrets.AZURE_PIPELINE_NAME }}
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}

